env:
  browser: true
  es6: true

extends:
  - airbnb
  - plugin:react/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - mobx

rules:
  react/prop-types: off
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx", ".ts", ".tsx"] }]
  no-unused-vars: off
  react/react-in-jsx-scope: off
